import type { Metadata } from "next";
import Link from "next/link";
import { EVENT_DATE_LONG, EVENT_NAME, SUDDEN_DEATH_RULE, VENUE_NAME } from "@/lib/tournament-details";

export const metadata: Metadata = { title: "Tournament Rules | Provo Tennis", description: `Rules for the 2026 ${EVENT_NAME}.` };

const sections = [
  { title: "1. Eligibility and registration", paragraphs: ["The event is open to players age 18 or older. Registration is not complete, and a place in the draw is not confirmed, until the $35 entry fee is successfully paid through Stripe.", "Players must provide accurate contact, age, and playing-level information. The organizer may correct divisions, seeds, or draw placement when reasonably necessary to create fair competition."] },
  { title: "2. Match format", bullets: ["Singles play in a 16-player field, with a championship draw and a consolation path intended to provide at least two matches per player, barring weather, injury, withdrawal, or circumstances outside the organizer’s control.", "Each match consists of four six-minute quarters.", "Every rally counts as one point. Games, advantage scoring, and traditional sets are not used.", "Each point begins with one serve only. A fault loses the point; there is no second serve.", "Service changes after every two points. Players change ends after each quarter or as directed by the organizer.", "The player with more points when a quarter ends wins that quarter. The first player to win three quarters wins the match.", SUDDEN_DEATH_RULE] },
  { title: "3. Timing and the buzzer", paragraphs: ["Players must be ready to begin when called. The organizer’s official clock controls. If the ending signal occurs during a live point, that point will be completed; a new point may not begin after the signal.", "Warm-up time is limited and may be shortened to keep the event on schedule. Repeated delay, arriving late, or failing to report may result in point penalties, loss of a quarter, default, or withdrawal from the draw."] },
  { title: "4. Calls, scoring, and disputes", paragraphs: ["Players make calls honestly and promptly on their own side of the court. If a player is unsure whether a ball was out, the ball is treated as good. Players should announce the score before each point and resolve disagreements calmly before continuing.", "When a dispute cannot be resolved, play must stop and the organizer or designated court monitor must be called. The organizer’s ruling on scoring, timing, conduct, scheduling, and tournament administration is final for this event."] },
  { title: "5. Conduct and sportsmanship", paragraphs: ["Players must treat opponents, volunteers, spectators, facilities, and equipment with respect. Racquet abuse, ball abuse, threats, discriminatory or abusive language, intentional cheating, unsafe play, or repeated disruption may result in a warning, point or quarter penalty, default, removal from the site, or disqualification without refund.", "Coaching during a match is not allowed unless the organizer announces otherwise. Spectators must not make line calls or interfere with play."] },
  { title: "6. Safety, equipment, and fitness", paragraphs: ["Players are responsible for arriving physically prepared, using safe tennis equipment and suitable court shoes, staying hydrated, and stopping play if they become injured or ill. Players must follow all facility rules and reasonable safety instructions.", "The organizer may stop or default a player when continued participation appears unsafe. This is a safety decision, not a medical assessment."] },
  { title: "7. Weather, schedule changes, and cancellation", paragraphs: ["Outdoor tennis is affected by rain, heat, wind, air quality, court conditions, and other circumstances outside the organizer’s control. Start times, match length, format, courts, and draws may be adjusted to complete the event safely and fairly.", "If the tournament is canceled, entry fees will be refunded. If a player withdraws, any refund may depend on whether the place can be filled from the waitlist and on costs already committed for the event."] },
  { title: "8. Final authority", paragraphs: ["These rules are designed for this community event and take priority over ordinary tennis scoring where they differ. Situations not covered here will be decided by the organizer using fairness, safety, sportsmanship, and the orderly completion of the tournament as guiding principles."] },
];

export default function RulesPage() {
  return <main className="legal-shell"><div className="legal-heading"><div className="eyebrow">Player agreement · Effective August 27, 2026</div><h1>Tournament<br/><em>Rules</em></h1><p>{EVENT_NAME} · {EVENT_DATE_LONG} · {VENUE_NAME}, Provo, Utah</p></div><div className="legal-card"><div className="legal-summary"><strong>The short version</strong><span>Play honestly. Keep moving. Respect the court. One serve, every point counts, and the organizer’s clock and rulings control.</span></div>{sections.map((section) => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets && <ul>{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul>}</section>)}<div className="legal-actions"><Link className="button dark" href="/register">Return to registration →</Link><Link href="/waiver">Read the liability waiver</Link></div></div></main>;
}
