import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Participation Waiver | Provo Tennis", description: "Participation waiver and release for the 2026 Provo Labor Day Tennis Tournament." };

export default function WaiverPage() {
  return <main className="legal-shell waiver-page"><div className="legal-heading"><div className="eyebrow">Important legal agreement · Effective August 26, 2026</div><h1>Participation<br/><em>Waiver</em></h1><p>Provo Labor Day Tennis Tournament · Monday, September 7, 2026 · Provo, Utah</p></div><article className="legal-card">
    <div className="legal-notice"><strong>Please read carefully.</strong><span>This agreement affects legal rights. By checking the waiver box and submitting registration, you confirm that you are at least 18 years old and agree electronically to every section below.</span></div>
    <section><h2>1. Voluntary participation</h2><p>I voluntarily choose to participate in the Provo Labor Day Tennis Tournament, including warm-ups, matches, practice, movement around the venue, and related event activities (collectively, the “Event”). I understand that I may decline to participate or stop participating at any time.</p></section>
    <section><h2>2. Acknowledgment and assumption of risk</h2><p>I understand that tennis and outdoor athletic events involve known and unknown risks of injury, illness, death, and property loss. These risks include, without limitation:</p><ul><li>rapid movement, overexertion, fatigue, dehydration, heat illness, and aggravation of existing medical conditions;</li><li>falls, slips, sudden stops, twisting, impact, and contact with balls, racquets, nets, fences, posts, court surfaces, equipment, other players, or spectators;</li><li>sprains, strains, fractures, concussions, eye injuries, and other minor or serious injuries;</li><li>weather, heat, sun exposure, wind, rain, lightning, air quality, wet or uneven surfaces, and changing court conditions;</li><li>equipment failure, acts or mistakes of other participants, limited supervision, delayed emergency response, and travel or movement at the venue; and</li><li>communicable illness or other risks that cannot be completely eliminated from a public event.</li></ul><p>I knowingly and voluntarily accept all risks arising from or related to my participation, whether known or unknown and whether described above or not. I am responsible for deciding whether I am physically able to participate safely.</p></section>
    <section><h2>3. Release and waiver of claims</h2><p>To the fullest extent permitted by Utah law, I release and waive claims against Provo Tennis, the tournament organizer, event volunteers, sponsors, contractors, officials, the host facility, court or property owners, and each of their respective representatives, employees, agents, successors, and assigns (collectively, the “Released Parties”) for personal injury, illness, death, property damage, or other loss arising from or related to the Event, including claims resulting from the ordinary negligence of a Released Party.</p><p>This release does not apply to gross negligence, reckless conduct, intentional misconduct, or any liability that cannot legally be waived.</p></section>
    <section><h2>4. Covenant not to sue and responsibility for claims</h2><p>I agree not to bring a claim against a Released Party for a matter covered by this waiver. To the fullest extent permitted by law, I will be responsible for claims, damages, or costs caused by my own negligent, reckless, or intentional conduct, including damage I cause to another person’s property.</p></section>
    <section><h2>5. Medical fitness and emergency care</h2><p>I confirm that I am at least 18 years old and am not aware of a condition that makes participation unsafe. I am responsible for consulting a medical professional when appropriate and for bringing any medication or protective equipment I may need.</p><p>If I cannot provide consent during an emergency, I authorize the organizer or event personnel to contact emergency services and arrange reasonably necessary first aid or medical care. I understand that the organizer does not provide medical insurance, and I accept responsibility for medical and transportation costs incurred on my behalf.</p></section>
    <section><h2>6. Rules and safety directions</h2><p>I agree to follow the Tournament Rules, facility requirements, and reasonable safety instructions. I understand that the organizer may modify, postpone, or cancel play; remove me from a match or the Event; or deny participation when reasonably necessary for safety, conduct, scheduling, or tournament administration.</p></section>
    <section><h2>7. Personal property</h2><p>I am responsible for my racquets, equipment, vehicle, valuables, and other personal property. The Released Parties are not responsible for loss, theft, or damage except to the extent liability cannot legally be waived.</p></section>
    <section><h2>8. Governing law and severability</h2><p>This agreement is governed by Utah law. If any provision is found unenforceable, it will be limited or removed only to the minimum extent necessary, and the remaining provisions will continue in effect. This document is intended to be interpreted as broadly as Utah law permits.</p></section>
    <section><h2>9. Electronic acknowledgment</h2><p>By checking the waiver box and submitting my registration, I acknowledge that I have read this entire agreement, understand it, have had the opportunity to ask questions or seek independent advice, and voluntarily agree to be bound by it. My electronic acceptance is intended as my electronic signature.</p></section>
    <div className="legal-advice"><strong>Organizer note</strong><span>This practical event waiver is tailored to the information currently available. Before relying on it as your final legal document, have a Utah attorney and the event’s insurer or venue review it.</span></div>
    <div className="legal-actions"><Link className="button dark" href="/register">Return to registration →</Link><Link href="/rules">Read the tournament rules</Link></div>
  </article></main>;
}
