import Link from "next/link";
import { Trophy, Clock3, Users, CalendarCheck, CircleDot, Sparkles } from "lucide-react";
import { getTournament } from "@/lib/data";

export const dynamic = "force-dynamic";

export default async function Home() {
  const { tournament: t, registered } = await getTournament(); const remaining = Math.max(t.capacity - registered, 0); const full = remaining === 0;
  const benefits = [[CalendarCheck,"Organized play","A well-run day with scheduled match times."],[Users,"Great competition","A welcoming field from recreational to advanced."],[CircleDot,"Fresh tennis balls","Quality balls supplied for tournament play."],[Trophy,"Winner’s prize","Play for the title—and a prize to be announced."],[Clock3,"Fast-match format","More action and less downtime on court."],[Sparkles,"A local tradition","Help launch a new community tournament series."]] as const;
  return <main><section className="hero"><div className="hero-main"><div className="eyebrow">Inaugural event · Provo, Utah</div><h1>Labor Day<br/><em>Tennis</em><br/>Tournament</h1><p className="hero-sub">{t.subtitle}</p><div className="hero-actions"><Link className="button" href="/register">{full ? "Join waitlist" : "Register to play"} →</Link><small>{remaining} of {t.capacity} spots remaining</small></div></div><aside className="hero-side"><div className="date-num">07</div><div className="date-month">SEPTEMBER ’26</div><div className="fact"><span>Day</span><span>Monday · Labor Day</span></div><div className="fact"><span>Place</span><span>{t.venue_confirmed ? t.venue_name : "Provo · Courts TBA"}</span></div><div className="fact"><span>Field</span><span>{t.capacity} singles players</span></div><div className="fact"><span>Entry</span><span>{t.entry_fee == null ? "Price coming soon" : `$${t.entry_fee}`}</span></div></aside></section>
  <div className="ticker"><div><span>ONE SERVE</span><span>●</span><span>EVERY POINT COUNTS</span><span>●</span><span>FOUR QUARTERS</span><span>●</span><span>FAST TENNIS</span></div></div>
  <section className="section"><div className="eyebrow">Why Provo Tennis?</div><h2 className="section-title">Tennis deserves a place on the local calendar.</h2><p className="lead">There are plenty of races, leagues, and community sporting events around Provo. We think tennis deserves some too.</p><p className="muted">This is the first of what we hope becomes a regular series. We’re starting intentionally small: sixteen players, a high-energy format, and one memorable day on the courts.</p></section>
  <section id="format" className="section dark-section"><div className="eyebrow">The format</div><div className="format-grid"><div><h2 className="section-title">Quick points.<br/>Big moments.</h2><p className="muted format-muted">A UTS-inspired format keeps every rally meaningful and every match moving.</p></div><div>{t.rules.map((rule)=><div className="rule" key={rule}>{rule}</div>)}</div><div></div><div className="quarter-card"><h3>First to 3 quarters wins</h3><div className="score"><span className="win">1</span><span>0</span><span className="win">1</span><span className="win">1</span></div><p className="disclaimer">This tournament is inspired by the UTS format and is not affiliated with UTS.</p></div></div></section>
  <section className="section"><div className="eyebrow">What you get</div><h2 className="section-title">Everything you need for a great day of tennis.</h2><div className="cards">{benefits.map(([Icon,title,copy])=><div className="card" key={title}><Icon size={30}/><b>{title}</b><span>{copy}</span></div>)}</div></section>
  <section className="split"><div className="schedule"><div className="eyebrow">{t.schedule_finalized ? "Official schedule" : "Tentative schedule"}</div><h2>Match day</h2><div className="schedule-list">{t.schedule.map((s)=><div className="schedule-row" key={s.time}><span>{s.time}</span><span>{s.label}</span></div>)}</div></div><div className="prize"><Trophy size={48}/><h2>Play for Provo.</h2><p className="lead prize-lead">{t.prize_description || "Winner’s prize to be announced"}</p><p>Details will be shared as they’re finalized.</p></div></section>
  <section className="section status-section"><div className="eyebrow centered">Registration is open</div><div className="spots">{remaining}<small>of {t.capacity} spots remaining</small></div><p className="muted status-copy">Recreational through competitive adult players are welcome. Tell us your level and we’ll seed the field thoughtfully.</p><Link href="/register" className="button dark">{full ? "Join the waitlist" : "Claim your spot"} →</Link></section>
  <section id="faq" className="section faq-section"><div className="eyebrow">Good to know</div><h2 className="section-title">Questions, answered.</h2><div className="faq">{t.faq.map((item)=><details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></section></main>;
}
