import { login,logout } from "./actions";
import { createSupabaseServer } from "@/lib/supabase-server";
import Link from "next/link";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
type PageProps<T extends string> = { searchParams: Promise<Record<string, string | string[] | undefined>> };
export const metadata={title:"Organizer | Provo Tennis"};
export default async function Page({searchParams}:PageProps<"/admin">){const p=await searchParams;if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return <main className="admin-shell"><div className="eyebrow">Organizer</div><h1>Admin setup</h1><div className="notice">Connect Supabase environment variables and run the included migration to activate secure organizer login, player management, and tournament settings.</div><Link className="button dark" href="/">View public site</Link></main>;
 const db=await createSupabaseServer();const{data:{user}}=await db.auth.getUser();if(!user)return <main className="admin-shell"><div className="eyebrow">Organizer access</div><h1>Welcome back.</h1><form action={login} className="form-card login-card">{p.error&&<div className="error">{p.error}</div>}<div className="field"><label htmlFor="email">Email</label><input id="email" name="email" type="email" required/></div><div className="field"><label htmlFor="password">Password</label><input id="password" name="password" type="password" required/></div><button className="button dark">Sign in →</button></form></main>;
 const[{data:t},{data:players}]=await Promise.all([db.from("tournaments").select("*").eq("slug","provo-labor-day-2026").single(),db.from("registrations").select("*").order("created_at",{ascending:false})]);const registered=players?.filter(x=>["registered","confirmed"].includes(x.status)).length||0;const waitlisted=players?.filter(x=>x.status==="waitlisted").length||0;return <main className="admin-shell"><div className="admin-head"><div><div className="eyebrow">Organizer dashboard</div><h1>{t?.name||"Labor Day Tournament"}</h1></div><form action={logout}><button className="button">Sign out</button></form></div><div className="admin-grid"><Stat n={t?.capacity||16} label="Capacity"/><Stat n={registered} label="Registered"/><Stat n={Math.max((t?.capacity||16)-registered,0)} label="Spots left"/><Stat n={waitlisted} label="Waitlisted"/></div><div className="admin-actions"><a className="button dark" href="/api/admin/registrations.csv">Export CSV</a><span>Settings and status changes can be managed securely in Supabase while the visual editor is finalized.</span></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Level</th><th>NTRP</th><th>UTR</th><th>Status</th><th>Seed</th></tr></thead><tbody>{players?.map(x=><tr key={x.id}><td><b>{x.first_name} {x.last_name}</b></td><td>{x.email}</td><td>{x.phone}</td><td>{x.self_rating}</td><td>{x.ntrp||"—"}</td><td>{x.utr||"—"}</td><td><span className="pill">{x.status}</span></td><td>{x.seed||"—"}</td></tr>)}</tbody></table></div></main>}
function Stat({n,label}:{n:number;label:string}){return <div className="stat"><strong>{n}</strong><span>{label}</span></div>}
